# Generated by Django 4.0.6 on 2022-12-06 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile_pic',
        ),
    ]
