# Generated by Django 4.0.6 on 2022-12-12 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arg_essay', '0003_remove_thesis_claim_thesis_declarative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiqaOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_sentence_one', models.CharField(max_length=500, null=True)),
                ('intro_quote_one', models.CharField(max_length=500, null=True)),
                ('quote_one', models.CharField(max_length=500, null=True)),
                ('analysis_one_one', models.CharField(max_length=500, null=True)),
                ('analysis_one_two', models.CharField(max_length=500, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TiqaThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_sentence_three', models.CharField(max_length=500, null=True)),
                ('intro_quote_three', models.CharField(max_length=500, null=True)),
                ('quote_three', models.CharField(max_length=500, null=True)),
                ('analysis_three_one', models.CharField(max_length=500, null=True)),
                ('analysis_three_two', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TiqaTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_sentence_two', models.CharField(max_length=500, null=True)),
                ('intro_quote_two', models.CharField(max_length=500, null=True)),
                ('quote_two', models.CharField(max_length=500, null=True)),
                ('analysis_two_one', models.CharField(max_length=500, null=True)),
                ('analysis_two_two', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='thesis',
            name='support_one',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='thesis',
            name='support_three',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='thesis',
            name='support_two',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Supports',
        ),
    ]
